#!/usr/bin/env python3
"""Generate Claude context and thin skill shims from project Agent Skills sources."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / ".agents/skills"
TARGET_ROOT = ROOT / ".claude/skills"
MARKER = "Generated by .agents/generate-claude.py"
CONTEXT_SOURCES = [ROOT / "AGENTS.md", ROOT / ".agents/claude-adapter.md"]
CONTEXT_TARGET = ROOT / "CLAUDE.md"


def read_utf8(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def render_skill(source: Path) -> bytes:
    text = read_utf8(source)
    end = text.find("\n---\n", 4)
    if not text.startswith("---\n") or end < 0:
        raise ValueError(f"invalid skill frontmatter: {source}")
    digest = hashlib.sha256(text.encode()).hexdigest()[:16]
    frontmatter = text[: end + len("\n---\n")]
    canonical = f".agents/skills/{source.parent.name}/SKILL.md"
    shim = (
        f"\n<!-- {MARKER}; source-sha256: {digest} -->\n\n"
        "# Canonical skill\n\n"
        f"Use the Read tool to load `{canonical}` from the repository root completely, "
        "then follow it as the authoritative instructions for this skill. Resolve relative "
        "references from that canonical skill directory.\n"
    )
    return (frontmatter + shim).encode()


def render_context() -> str:
    body = "\n\n---\n\n".join(read_utf8(path).strip() for path in CONTEXT_SOURCES) + "\n"
    digest = hashlib.sha256(body.encode()).hexdigest()[:16]
    return (
        f"<!-- {MARKER}; source-sha256: {digest} -->\n"
        "<!-- Edit AGENTS.md or .agents/claude-adapter.md, then regenerate. -->\n\n"
        f"{body}"
    )


def source_skills() -> dict[str, dict[Path, bytes]]:
    skills: dict[str, dict[Path, bytes]] = {}
    for skill_file in sorted(SOURCE_ROOT.glob("*/SKILL.md")):
        skills[skill_file.parent.name] = {Path("SKILL.md"): render_skill(skill_file)}
    return skills


def target_files(directory: Path) -> set[Path]:
    if not directory.is_dir():
        return set()
    return {path.relative_to(directory) for path in directory.rglob("*") if path.is_file()}


def is_generated(directory: Path) -> bool:
    skill = directory / "SKILL.md"
    return skill.is_file() and MARKER in read_utf8(skill)


def write_skill(name: str, files: dict[Path, bytes]) -> None:
    target = TARGET_ROOT / name
    temporary = TARGET_ROOT / f".{name}.tmp.{os.getpid()}"
    shutil.rmtree(temporary, ignore_errors=True)
    try:
        for relative, content in files.items():
            output = temporary / relative
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(content)
        if target.is_symlink():
            target.unlink()
        elif target.exists():
            shutil.rmtree(target)
        temporary.rename(target)
    finally:
        shutil.rmtree(temporary, ignore_errors=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    drifted: list[Path] = []
    context = render_context()
    if args.check:
        if not CONTEXT_TARGET.exists() or read_utf8(CONTEXT_TARGET) != context:
            drifted.append(CONTEXT_TARGET)
    else:
        CONTEXT_TARGET.write_text(context, encoding="utf-8")
        print(CONTEXT_TARGET.relative_to(ROOT))

    expected = source_skills()
    for name, files in expected.items():
        target = TARGET_ROOT / name
        if args.check:
            if target.is_symlink() or target_files(target) != set(files) or any(
                not (target / relative).is_file() or (target / relative).read_bytes() != content
                for relative, content in files.items()
            ):
                drifted.append(target)
        else:
            write_skill(name, files)
            print(target.relative_to(ROOT))

    for target in TARGET_ROOT.iterdir():
        if not target.is_dir() or target.name in expected or not is_generated(target):
            continue
        if args.check:
            drifted.append(target)
        else:
            shutil.rmtree(target)
            print(f"removed {target.relative_to(ROOT)}")

    if drifted:
        for target in drifted:
            print(f"drift: {target.relative_to(ROOT)}")
        return 1
    if args.check:
        print("generated Claude context and skills are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
