#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

SCRIPT = Path(__file__).with_name("generate-claude.py")
SPEC = importlib.util.spec_from_file_location("generate_claude", SCRIPT)
assert SPEC and SPEC.loader
GENERATOR = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(GENERATOR)


class ClaudeSkillShimTest(unittest.TestCase):
    def test_render_skill_keeps_discovery_metadata_without_copying_body(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "example-skill" / "SKILL.md"
            source.parent.mkdir()
            source.write_text(
                "---\n"
                "name: example-skill\n"
                "description: Finds the canonical instructions.\n"
                "---\n\n"
                "# AUTHORITATIVE_BODY_MUST_NOT_BE_COPIED\n",
                encoding="utf-8",
            )

            rendered = GENERATOR.render_skill(source).decode()

        self.assertTrue(
            rendered.startswith(
                "---\n"
                "name: example-skill\n"
                "description: Finds the canonical instructions.\n"
                "---\n"
            )
        )
        self.assertIn("Generated by .agents/generate-claude.py", rendered)
        self.assertIn(".agents/skills/example-skill/SKILL.md", rendered)
        self.assertIn("Read", rendered)
        self.assertNotIn("AUTHORITATIVE_BODY_MUST_NOT_BE_COPIED", rendered)

    def test_source_skills_does_not_mirror_canonical_attachments(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source_root = Path(directory) / "skills"
            skill = source_root / "example-skill"
            (skill / "references").mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\n"
                "name: example-skill\n"
                "description: Uses a canonical reference.\n"
                "---\n\n"
                "Read references/details.md.\n",
                encoding="utf-8",
            )
            (skill / "references/details.md").write_text("canonical only\n", encoding="utf-8")

            with patch.object(GENERATOR, "SOURCE_ROOT", source_root):
                skills = GENERATOR.source_skills()

        self.assertEqual(set(skills["example-skill"]), {Path("SKILL.md")})


if __name__ == "__main__":
    unittest.main()
