/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/renderer/**/*.{html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        bg: 'var(--color-bg)',
        'bg-panel': 'var(--color-bg-panel)',
        surface: 'var(--color-surface)',
        'surface-2': 'var(--color-surface-2)',
        'surface-3': 'var(--color-surface-3)',
        'surface-active': 'var(--color-surface-active)',
        'surface-input': 'var(--color-surface-input)',
        'surface-selected': 'var(--color-surface-selected)',
        'surface-thumb': 'var(--color-surface-thumb)',
        'surface-splitter': 'var(--color-surface-splitter)',
        border: 'var(--color-border)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-strong': 'var(--color-border-strong)',
        text: 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-dim': 'var(--color-text-dim)',
        'code-blue': 'var(--color-code-blue)',
        'code-orange': 'var(--color-code-orange)',
        'code-label': 'var(--color-code-label)',
        'code-number': 'var(--color-code-number)',
        'code-keyword': 'var(--color-code-keyword)',
        'status-warn': 'var(--color-status-warn)',
        'status-error': 'var(--color-status-error)',
        'status-success': 'var(--color-status-success)',
        'danger-bg': 'var(--color-danger-bg)',
        'warn-bg': 'var(--color-warn-bg)',
        'warn-border': 'var(--color-warn-border)',
        overlay: 'var(--color-overlay)',
        'overlay-heavy': 'var(--color-overlay-heavy)',
        'sim-bg': 'var(--color-sim-bg)',
        'sim-bottom': 'var(--color-sim-bottom)',
        'sim-screen': 'var(--color-sim-screen)',
        'phone-shell': 'var(--color-phone-shell)',
        'phone-border': 'var(--color-phone-border)',
      },
      fontFamily: {
        sans: ['var(--font-family)'],
        mono: ['var(--font-family-mono)'],
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
    },
  },
  plugins: [],
}
