export { installConsoleInstrumentation } from '../instrumentation/console.js'
export { installAppDataInstrumentation, sendAllAppData } from '../instrumentation/app-data.js'
export { installWxmlInstrumentation, sendWxmlTree, setupWxmlObserver } from '../instrumentation/wxml.js'
export { installSimulatorBridge } from '../runtime/bridge.js'
export { setupApiCompatHook } from '../shared/api-compat.js'
